export {default as Navbar} from './Navbar'
export {default as Home} from './Home'
export {default as About} from './About'
export {default as Team} from './Team'
export {default as Events} from './Events'
export {default as Photos} from './Photos'